name: pyhep-2023

channels:
  - conda-forge

dependencies:
  - python=3.10
  - awkward==2.4.5
  - numba==0.57.1
  - cppyy==2.4.2
  - root==6.28.4
  - julia==1.9.3
  - pip

# conda-lock only
platforms:
  - linux-64
  - osx-64
